const vocabulary = {
// 10 Char Password = 4 letter words
    4: {
        adj: [
            // Original
            "warm", "cold", "mild", "tart", "sour", "rich", "pure", "soft", "hard", "oily", 
            "fine", "nice", "good", "best", "neat", "cool", "bold", "calm", "fast", "slow", 
            "wild", "safe", "wise", "tall", "deep", "holy", "epic", "vast", "kind", "fair", 
            "free", "real", "true", "keen", "loud", "glad", "busy", "easy", "sole", "firm", 
            "flat", "zany", "gold", "rosy", "airy", "lush", "posh", "mama", "chef", "blue",
            // New Additions (Strictly 4 Letters)
            "acid", "aged", "avid", "bald", "bare", "bent", "cyan", "damp", "dark", "dead",
            "deaf", "dear", "deft", "dire", "done", "dull", "edgy", "even", "evil", "fond",
            "full", "gray", "grey", "grim", "half", "hazy", "high", "huge", "hurt", "idle",
            "just", "lame", "last", "late", "lazy", "lean", "left", "like", "limp", "lime",
            "live", "lone", "long", "male", "many", "mean", "mere", "mini", "mute", "navy",
            "near", "next", "numb", "only", "open", "pale", "pink", "poor", "rare", "ripe",
            "rude", "same", "sick", "slim", "sore", "sure", "tame", "taut", "teal", "thin",
            "tidy", "tiny", "ugly", "vain", "wary", "weak", "wide", "worn", "iced", "raws"
        ],
        noun: [
            // Original
            "wine", "fork", "dish", "menu", "chef", "cook", "cake", "meal", "meat", "fish", 
            "clam", "crab", "veal", "lamb", "pork", "beef", "salt", "herb", "bowl", "cafe", 
            "deli", "soup", "rice", "bean", "pear", "lime", "soda", "tart", "oven", "tray", 
            "kiwi", "plum", "mint", "sage", "rose", "tuna", "duck", "corn", "moon", "star", 
            "bird", "leaf", "tree", "rock", "wave", "fire", "wind", "snow", "arch", "area", 
            // New Additions (Strictly 4 Letters)
            "army", "atom", "aunt", "aura", "baby", "back", "bail", "bait", "ball", "band", 
            "bank", "bark", "barn", "base", "bath", "bead", "beak", "beam", "bear", "beat", 
            "beer", "bell", "belt", "bend", "bias", "bike", "bill", "bite", "blow", "boat", 
            "body", "bolt", "bond", "bone", "book", "boom", "boot", "boss", "bulk", "bull", 
            "bump", "burn", "bush", "cage", "calf", "call", "camp", "cane", "card", "care", 
            "cart", "case", "cash", "cast", "cave", "cell", "cent", "chin", "chip", "city", 
            "clan", "clap", "claw", "clay", "clip", "club", "clue", "coal", "coat", "code", 
            "coil", "coin", "coke", "colt", "comb", "cone", "cool", "cord", "core", "cork", 
            "cost", "cove", "crew", "crop", "crow", "cube", "cult", "curb", "cure", "curl", 
            "cyst", "dada", "dame", "damp", "dare", "dash", "data", "date", "dawn", "days", 
            "daze", "deal", "dean", "dear", "debt", "deck", "deed", "deep", "deer", "dent", 
            "desk", "dial", "dice", "diet", "dime", "dine", "dirt", "disc", "disk", "dive", 
            "dock", "doll", "dome", "door", "dose", "dove", "down", "drag", "draw", "drop", 
            "drug", "drum", "duel", "duet", "duke", "dune", "dusk", "dust", "duty", "earl", 
            "ease", "east", "edge", "envy", "epic", "exit", "face", "fact", "fade", "fail", 
            "fair", "fall", "fame", "farm", "fate", "fear", "feat", "feed", "feel", "fern", 
            "feud", "file", "film", "fist", "flag", "flaw", "flea", "flow", "flue", "foam", 
            "foil", "fold", "folk", "food", "fool", "foot", "ford", "form", "fort", "fowl", 
            "frog", "fuel", "fund", "fury", "fuse", "fuss", "gain", "gait", "gala", "game", 
            "gang", "gasp", "gate", "gaze", "gear", "gene", "germ", "gift", "girl", "glee", 
            "glow", "glue", "goal", "goat", "gold", "golf", "gong", "gown", "grab", "gram", 
            "grid", "grin", "grip", "grit", "grow", "grub", "gulf", "gull", "guru", "gust", 
            "hail", "hair", "hall", "halo", "halt", "hand", "hare", "harp", "hate", "hawk", 
            "head", "heal", "heap", "hear", "heat", "heel", "heir", "hell", "helm", "help", 
            "herd", "hero", "hill", "hint", "hire", "hiss", "hold", "hole", "home", "hood", 
            "hook", "hoop", "hope", "horn", "hose", "host", "hour", "howl", "hull", "hunt", 
            "hurt", "hype", "icon", "idea", "idol", "inch", "info", "iron", "isle", "itch", 
            "item", "jack", "jail", "jazz", "jeep", "jest", "jinx", "joke", "jolt", "jump", 
            "jury", "just", "jute", "kale", "keel", "keep", "kelp", "kick", "kill", "kiln", 
            "kind", "king", "kiss", "kite", "knee", "knot", "lace", "lack", "lady", "lake", 
            "land", "lane", "lark", "lash", "lass", "lava", "lawn", "lead", "leak", "leap", 
            "lens", "liar", "lice", "lick", "life", "lift", "limb", "line", "link", "lion", 
            "list", "load", "loaf", "loan", "lock", "loft", "logo", "look", "loom", "loop", 
            "lord", "loss", "lost", "love", "luck", "lump", "lung", "lure", "lush", "lute", 
            "maid", "mail", "main", "make", "male", "mall", "malt", "mane", "mark", "mars", 
            "mask", "mass", "mast", "mate", "math", "maze", "melt", "memo", "mesh", "mess", 
            "mile", "milk", "mill", "mind", "mine", "miss", "mist", "mite", "moan", "moat", 
            "mode", "mold", "mole", "mood", "moss", "moth", "move", "mule", "muse", "mush", 
            "musk", "must", "mute", "myth", "nail", "name", "navy", "neck", "need", "neon", 
            "nest", "news", "nick", "node", "noir", "nose", "note", "noun", "oath", "odds", 
            "odor", "okay", "omen", "omit", "once", "onyx", "opal", "open", "oral", "orca", 
            "oval", "pace", "pack", "pact", "page", "pain", "pair", "palm", "pane", "park", 
            "part", "pass", "past", "path", "peak", "peas", "peck", "peer", "pest", "pick", 
            "pier", "pile", "pill", "pine", "pink", "pint", "pipe", "pity", "plan", "play", 
            "plea", "plot", "plug", "plum", "plus", "poem", "poet", "pole", "poll", "pond", 
            "pony", "pool", "pope", "pork", "port", "pose", "post", "pray", "prey", "prop", 
            "puff", "pull", "pulp", "pump", "punk", "push", "quiz", "race", "rack", "raft", 
            "rage", "raid", "rail", "rain", "rake", "ramp", "rank", "rant", "rash", "rate", 
            "rave", "read", "rear", "reed", "reef", "reel", "rent", "rest", "rice", "rich", 
            "ride", "rift", "ring", "riot", "rise", "risk", "rite", "road", "roar", "robe", 
            "rock", "role", "roll", "roof", "room", "root", "rope", "rose", "ruby", "ruin", 
            "rule", "rush", "rust", "sack", "safe", "sail", "sale", "sand", "sane", "sash", 
            "save", "scan", "scar", "seal", "seam", "sear", "seat", "seed", "seek", "self", 
            "sell", "send", "shed", "ship", "shoe", "shop", "shot", "show", "shut", "side", 
            "sign", "silk", "silo", "silt", "sink", "sire", "site", "size", "skew", "skid", 
            "skin", "skip", "skit", "slab", "slam", "slap", "sled", "slip", "slit", "slot", 
            "slug", "snag", "snap", "soap", "sock", "soil", "sold", "sole", "solo", "song", 
            "soon", "sore", "sort", "soul", "span", "spar", "spat", "spin", "spit", "spot", 
            "spur", "stab", "stag", "stay", "stem", "step", "stew", "stir", "stop", "stow", 
            "stub", "stud", "stun", "suit", "surf", "swan", "sway", "swim", "tack", "taco", 
            "tail", "take", "tale", "talk", "tank", "tape", "task", "taxi", "teak", "team", 
            "tear", "tech", "tell", "tent", "term", "test", "text", "tide", "tidy", "tile", 
            "tilt", "time", "tint", "tire", "toad", "toll", "tomb", "tone", "tool", "toss", 
            "tour", "town", "tram", "trap", "trek", "trim", "trip", "trot", "tube", "tuna", 
            "tune", "turf", "turn", "twig", "twin", "type", "unit", "user", "vase", "veil", 
            "vein", "vent", "verb", "vest", "veto", "vibe", "vice", "view", "vine", "visa", 
            "vise", "void", "volt", "vote", "wage", "waif", "wait", "wake", "walk", "wall", 
            "wand", "want", "ward", "ware", "warm", "warn", "warp", "wash", "wasp", "wave", 
            "wear", "weed", "week", "well", "west", "whim", "whip", "wife", "wild", "will", 
            "wine", "wing", "wink", "wire", "wish", "wolf", "wood", "wool", "word", "work", 
            "worm", "wrap", "yard", "yarn", "year", "yelp", "yoga", "yolk", "zeal", "zero", 
            "zinc", "zone", "zoom"
        ]
    },
// 12 Char Password = 5 letter words
    5: {
        adj: [
            // Previous words...
            // Additional Words
            "alert", "alive", "alone", "awful", "blank", "bleak", "blond", "bogus", "bored", "bossy",
            "bumpy", "burnt", "cagey", "chile", "close", "crazy", "cruel", "curly", "curvy", "dense",
            "eager", "elite", "false", "fuzzy", "giddy", "hasty", "jolly", "jumpy", "known", "legal",
            "manic", "meaty", "messy", "milky", "misty", "mixed", "muddy", "murky", "mushy", "musty",
            "naive", "needy", "nerdy", "noisy", "nutty", "petty", "pious", "plush", "puffy", "pushy",
            "rainy", "regal", "right", "risky", "rocky", "rural", "rusty", "salty", "sandy", "saucy",
            "scary", "shaky", "sheer", "shiny", "short", "silly", "slick", "smoky", "snowy", "sober",
            "soggy", "solar", "sorry", "sound", "spare", "stale", "stony", "sunny", "tasty",
            "tense", "tepid", "timid", "total", "toxic", "urban", "usual", "viral", "vocal", "wacky",
            "weird", "windy", "wrong", "zesty", "aging", "angry", "aptly", "badly", "baggy", "balmy"
        ],
        noun: [
            // Previous words...
            // Additional Words
            "alarm", "album", "arrow", "bacon", "badge", "baker", "beast", "bench", "bison", "blade",
            "blend", "bliss", "bonus", "booth", "boost", "booty", "broom", "brush", "buddy", "bunch",
            "bunny", "cabin", "cable", "camel", "canal", "candy", "canoe", "canon", "cargo", "catch",
            "chaos", "charm", "cheat", "cheek", "cheer", "chess", "chili", "choir", "cigar", "clash",
            "clerk", "click", "cliff", "cloak", "clone", "cloth", "cloud", "clown", "cobra", "cocoa",
            "comic", "couch", "cough", "crack", "craft", "crane", "crash", "crate", "crawl", "craze",
            "creek", "crest", "crime", "cross", "crust", "curve", "daddy", "daisy", "demon", "diary",
            "diner", "disco", "ditch", "diver", "donut", "drain", "drift", "drill", "drone", "drove",
            "dummy", "eagle", "elbow", "email", "essay", "fable", "fairy", "feast", "fence", "ferry",
            "fiber", "fifty", "flame", "flash", "flask", "flesh", "flock", "flood", "flour", "fluid",
            "flush", "folly", "forum", "fraud", "freak", "frost", "frown", "ghost", "glare", "glaze",
            "globe", "gloom", "glory", "glove", "goose", "grace", "grade", "grain", "graph", "grate",
            "grave", "gravy", "greed", "grief", "grill", "groom", "grove", "growl", "guard", "guess",
            "guest", "guild", "habit", "hedge", "hello", "heron", "hippo", "hobby", "honor", "humor",
            "idiot", "igloo", "inbox", "index", "input", "issue", "ivory", "jeans", "jelly", "jewel",
            "judge", "karma", "kayak", "kebab", "kitty", "koala", "label", "labor", "laser", "latch",
            "laugh", "layer", "leech", "lemur", "lever", "limit", "linen", "liner", "liver", "llama",
            "lobby", "logic", "lotus", "lover", "lunch", "lyric", "macro", "madam", "maize", "mamba",
            "mango", "mania", "manor", "maple", "march", "marsh", "match", "medal", "media", "medic",
            "merit", "metal", "meter", "metro", "miner", "model", "modem", "money", "month", "moose"
        ]
    },
// 14 Char Password = 6 letter words
    6: {
        adj: [
            // Original (Verified)
            "creamy", "garlic", "cheesy", "tender", "hearty", "smooth", "bright", "golden", "purple", "orange",
            "silver", "copper", "bronze", "active", "actual", "afraid", "annual", "asleep", "better", "bitter",
            "boring", "broken", "casual", "clever", "common", "decent", "divine", "double", "driven", "entire",
            "exotic", "expert", "famous", "fierce", "formal", "frozen", "future", "gentle", "global", "guilty",
            "honest", "hungry", "insane", "little", "lonely", "lovely", "mental", "middle", "mobile", "modern",
            // New Additions (Verified 6-Letters)
            "modest", "narrow", "native", "normal", "polite", "pretty", "proper", "public", "random", "remote",
            "robust", "rotten", "sacred", "secret", "senior", "severe", "silent", "simple", "single", "skinny",
            "sleepy", "social", "steady", "sticky", "stormy", "strong", "stupid", "sudden", "subtle", "superb",
            "tragic", "unfair", "unique", "united", "urgent", "useful", "vacant", "visual", "worthy", "weekly",
            "wicked", "wooden", "yellow", "absent", "absurd", "breezy", "chilly", "cloudy", "deadly", "glossy",
            // Extra Additions (Strictly 6-Letters)
            "abrupt", "acidic", "adored", "amazed", "amused", "astute", "biased", "blonde", "bloody", "bodily",
            "brainy", "brazen", "bubbly", "catchy", "choice", "chunky", "classy", "clumsy", "coarse", "costly",
            "creepy", "crispy", "cuddly", "custom", "daring", "direct", "dismal", "dreary", "earthy", "ending", 
            "exotic", "family", "fickle", "filthy", "fitted", "flimsy", "floral", "fluent", "fluffy", "freaky", 
            "friend", "frosty", "genial", "gifted", "glassy", "gloomy", "greedy", "grumpy", "hollow", "horrid", 
            "humble", "hybrid", "immune", "impure", "inland", "intact", "intent", "jovial", "joyful", "junior", 
            "kindly", "lawful", "linear", "liquid", "lively", "loving", "luxury", "manual", "marine", "mature", 
            "medium", "mellow", "menial", "mighty", "mutual", "mystic", "nearby", "numbly", "opaque", "openly", 
            "placid", "poetic", "potent", "primal", "prized", "prompt", "quaint", "racial", "rarely", "recent", 
            "richly", "ritual", "rudely", "rustic", "savage", "scanty", "scarce", "scenic", "second", "secure", 
            "select", "serene", "sexual", "shabby", "shaggy", "shrewd", "shrill", "sketch", "slinky", "sloppy", 
            "slowly", "smelly", "sneaky", "snobby", "solemn", "somber", "sordid", "sparse", "speedy", "spider", 
            "spiral", "spirit", "splash", "spoilt", "spooky", "sporty", "spotty", "stable", "stingy", "strict", 
            "sturdy", "sweaty", "timely", "tribal", "tricky", "uneven", "unsafe", "unwell", "vacant", "varied", 
            "vastly", "verbal", "viable", "wasted", "wildly"
        ],
        noun: [
            // Original (Verified)
            "tomato", "cheese", "garlic", "pepper", "butter", "cookie", "muffin", "yogurt", "noodle", "shrimp",
            "salmon", "turkey", "salami", "panini", "bakery", "buffet", "dinner", "supper", "bistro", "waiter",
            "napkin", "candle", "garden", "flower", "forest", "jungle", "desert", "island", "planet", "galaxy",
            "rocket", "engine", "system", "method", "theory", "action", "advice", "agency", "agenda", "amount",
            "animal", "answer", "appeal", "aspect", "attack", "author", "basket", "battle", "beauty", "belief",
            // New Additions (Verified 6-Letters)
            "border", "bottle", "bottom", "branch", "breath", "bridge", "budget", "burden", "button", "camera",
            "cancer", "career", "castle", "cattle", "center", "chance", "change", "charge", "choice", "church",
            "circle", "client", "closet", "coffee", "collar", "column", "corner", "cotton", "county", "couple",
            "course", "cousin", "credit", "crisis", "damage", "danger", "debate", "degree", "demand", "design",
            "desire", "detail", "device", "doctor", "dollar", "domain", "driver", "editor", "effect", "effort",
            // Extra Additions (Strictly 6-Letters)
            "abacus", "accent", "accord", "addict", "aerial", "affair", "affect", "airbag", "alcove", "almond",
            "alpaca", "ambush", "amulet", "anchor", "anklet", "anthem", "antics", "anvils", "arcade", "archer",
            "armada", "armour", "armpit", "arrest", "arrival", "arrows", "artist", "assets", "asylum", "attire",
            "august", "avatar", "avenue", "baboon", "backer", "backup", "badger", "bagels", "bakers", "ballet", 
            "ballot", "bamboo", "banana", "bandit", "bangle", "banker", "banner", "barber", "barley", "barrel", 
            "barrow", "barter", "basset", "batter", "beacon", "beagle", "beaker", "beaver", "beckon", "bedbug", 
            "bedlam", "beetle", "beggar", "behalf", "belfry", "bender", "berets", "betray", "bibles", "biceps", 
            "bidder", "bigwig", "bikini", "billet", "biopsy", "birdie", "births", "bisect", "bishop", "blades", 
            "blamer", "blazer", "bleach", "blends", "blight", "blinds", "blocks", "blonds", "bloods", "blooms", 
            "blouse", "blower", "boards", "boasts", "boater", "bodies", "boiler", "bolder", "bonbon", "bonnet", 
            "boogie", "bookie", "booths", "bootie", "borrow", "bosses", "boughs", "bounce", "bounds", "bounty", 
            "bowler", "boxcar", "boxers", "braces", "brains", "brakes", "brands", "brandy", "breach", "breads", 
            "breaks", "breast", "breeze", "brewer", "bribes", "bricks", "bridal", "brides", "briefs", "bronco", 
            "brooch", "broods", "brooks", "brooms", "broths", "browns", "browse", "bruise", "brunch", "bubble", 
            "bucket", "buckle", "buffer", "bugger", "bugles", "builds", "bulges", "bullet", "bumble", "bumper", 
            "bundle", "bunker", "bureau", "burger", "burial", "burlap", "burner", "burrow", "bushel", "bushes", 
            "busker", "buster", "bustle", "butane", "butler", "buyers", "buzzer", "bypass", "cabins", "cables", 
            "cactus", "caddie", "cadets", "caesar", "caller", "camper", "campus", "canals", "canary", "cancel", 
            "candor", "canine", "canned", "cannon", "canoes", "canopy", "canvas", "canyon", "capers", "carbon", 
            "caress", "carpet", "carrot", "cartel", "carton", "carver", "cashew", "casino", "casket", "caster", 
            "catchy", "catgut", "caucus", "causes", "caveat", "cavern", "caviar", "cavity", "celery", "cellar", 
            "cement", "census", "cereal", "chaise", "chalet", "chalky", "chapel", "charms", "charts", "chaser", 
            "chaste", "chatty", "cheats", "checks", "cheeky", "cheers", "cherub", "chests", "chesty", "chewer", 
            "chicks", "chiefs", "chills", "chilly", "chimes", "chimps", "chinks", "chirpy", "chisel", "choirs", 
            "choked", "choker", "choose", "choppy", "choral", "chords", "chores", "chorus", "chrome", "chunks", 
            "chunky", "churns", "chutes", "cicada", "cigars", "cinema", "cipher", "circus", "cities", "citrus", 
            "claims", "clamor", "clamps", "clause", "cleans", "clears", "cleats", "cleave", "clergy", "clerks", 
            "clicks", "cliffs", "climax", "clinic", "clique", "clocks", "clones", "closed", "closer", "cloths", 
            "clouds", "clover", "clowns", "clumps", "clutch", "coasts", "coated", "cobalt", "cobble", "cobweb", 
            "cocoon", "coffin", "cognac", "cohort", "coiled", "coiner", "colder", "collie", "colony", "colors", 
            "combat", "comedy", "comets", "comics", "coming", "commit", "compel", "comply", "concur", "condor", 
            "confer", "conman", "consul", "convex", "convey", "convoy", "cooler", "cooped", "copier", "copies", 
            "coping", "copter", "corals", "cornet", "corona", "corpse", "corpus", "corral", "corset", "cortex", 
            "cosmic", "cosmos", "costly", "coughs", "counts", "courts", "covers", "covert", "cowboy", "coyote", 
            "cracks", "cradle", "crafty", "cramps", "cranes", "cranks", "cranky", "crates", "crater", "crayon", 
            "creaks", "creaky", "creams", "crease", "create", "creeks", "creepy", "creole", "crests", "criers", 
            "crimes", "cringe", "croaks", "crooks", "crotch", "crouch", "crowds", "crowns", "cruise", "crumbs", 
            "crunch", "crusts", "crusty", "crying", "crypts", "cuckoo", "cuddle", "cudgel", "cupful", "curate", 
            "curfew", "curios", "cursor", "curves", "custom", "cutout", "cutter", "cycles", "cymbal", "cynics", 
            "cypher"
        ]
    },
// 16 Char Password = 7 letter words
    7: {
        adj: [
            // Original
            "roasted", "crunchy", "organic", "natural", "healthy", "savoury", "amazing", "antique", "anxious", "average",
            "awesome", "awkward", "bizarre", "braided", "brother", "careful", "classic", "complex", "correct", "corrupt",
            "curious", "current", "damaged", "defiant", "delight", "distant", "diverse", "dynamic", "eastern", "elderly",
            "elegant", "endless", "ethical", "excited", "extreme", "federal", "foreign", "forever", "fragile", "general",
            "genuine", "gradual", "harmful", "helpful", "illegal", "initial", "instant", "intense", "jealous", "liberal",
            // New Additions
            "logical", "massive", "maximum", "medical", "minimal", "musical", "mystery", "nervous", "neutral", "nuclear",
            "obvious", "optimal", "painful", "patient", "perfect", "plastic", "popular", "premium", "present", "primary",
            "private", "radical", "regular", "related", "routine", "selfish", "serious", "shallow", "similar", "special",
            "strange", "subject", "supreme", "thermal", "thirsty", "typical", "unknown", "unusual", "various", "violent",
            "visible", "wealthy", "western", "willing", "written", "abiding", "adamant", "angrier", "applied", "aquatic"
        ],
        noun: [
            // Original
            "lasagna", "ravioli", "spinach", "arugula", "sausage", "chicken", "lobster", "dessert", "custard", "pudding",
            "brownie", "truffle", "kitchen", "balcony", "terrace", "pizzazz", "calzone", "risotto", "polenta", "gnocchi",
            "ability", "absence", "academy", "account", "address", "advance", "airline", "airport", "alcohol", "analyst",
            "anxiety", "article", "attempt", "auction", "balance", "banking", "barrier", "battery", "bedroom", "benefit",
            "bicycle", "biology", "blanket", "brother", "cabinet", "captain", "capture", "caution", "ceiling", "century",
            // New Additions
            "chamber", "channel", "chapter", "charity", "charter", "circuit", "citizen", "classic", "climate", "clothes",
            "college", "comfort", "command", "comment", "company", "compass", "complex", "concept", "concern", "concert",
            "conduct", "contact", "contest", "context", "control", "convert", "cooking", "council", "counsel", "counter",
            "country", "courage", "creator", "culture", "curtain", "cushion", "defense", "deficit", "deposit", "despair",
            "destiny", "diamond", "digital", "disease", "display", "dispute", "divorce"
        ]
    },
// 18 Char Password = 8 letter words
    8: {
        adj: [
            // Original (Fixed & Verified 8 letters)
            "homemade", "seasoned", "aromatic", "delicate", "generous", "tropical", "absolute", "abstract",
            "academic", "accepted", "accurate", "adequate", "advanced", "artistic", "athletic", "attached",
            "balanced", "becoming", "bitterly", "cheerful", "chemical", "circular", "civilian", "clinical",
            "colonial", "colorful", "colossal", "combined", "complete", "composed", "concrete", "confused",
            "constant", "contrary", "creative", "critical", "cultural", "definite", "detailed", "distinct",
            "dramatic", "educated", "electric", "eligible", "emphatic", "employed", "enormous", "entirely",
            "equipped", "especial", "everyday", "extended", "external", "familiar", "faithful", "feminine",
            "flexible", "formerly", "friendly", "glorious", "grateful", "gripping", "habitual", "handsome",
            "harmless", "helpless", "historic", "homeless", "honestly", "horrible", "hospital", "humorous",
            "imminent", "impolite", "incident", "inclined", "included", "indicate", "infinite", "informal",
            "inherent", "innocent", "inspired", "integral", "intended", "intimate", "isolated", "literary",
            "lovelier", "luckiest", "luminous", "lustrous", "majestic", "marginal", "material", "medieval",
            "memorial", "merchant", "military", "moderate", "monetary", "multiple", "national", "negative",
            "numerous", "official", "opposite", "optional", "ordinary", "original", "parallel", "peaceful",
            "peculiar", "periodic", "personal", "physical", "pleasant", "positive", "possible", "powerful",
            "precious", "previous", "probable", "profound", "properly", "proposed", "rational", "reactive",
            "regional", "relative", "relevant", "reliable", "repeated", "resident", "romantic", "shameful",
            "shopping", "sleeping", "slightly", "slippery", "specific", "splendid", "standard", "straight",
            "stranger", "striking", "stunning", "suitable", "superior", "tangible", "teaching", "terrible",
            "thorough", "together", "training", "ultimate", "unlikely", "valuable", "variable", "vertical",
            "vigorous", "virtuous", "visiting", "westerly", "whatever", "whenever", "wherever", "wireless",
            "worrying", "youngest"
        ],
        noun: [
            // Original (Fixed & Verified 8 letters)
            "macaroni", "rigatoni", "mushroom", "zucchini", "sandwich", "focaccia", "tiramisu", "espresso",
            "parmesan", "linguine", "accident", "accuracy", "activist", "activity", "addition", "adoption",
            "advocate", "airplane", "alliance", "altitude", "ambition", "ancestor", "anecdote", "appetite",
            "applause", "approach", "aquarium", "argument", "armchair", "artifact", "assembly", "attitude",
            "audience", "autonomy", "backbone", "backdrop", "backyard", "bacteria", "bankrupt", "baseball",
            "basement", "bathroom", "beverage", "birthday", "blessing", "boundary", "brochure", "building",
            "bulletin", "business", "calendar", "campaign", "capacity", "cardinal", "carriage", "casualty",
            "category", "cemetery", "ceremony", "champion", "children", "clothing", "cocktail", "collapse",
            "commerce", "compound", "computer", "conflict", "congress", "conquest", "contract", "contrast",
            "corridor", "coverage", "creation", "creature", "criminal", "criteria", "crossing", "cupboard",
            "currency", "customer", "cylinder", "darkness", "database", "daughter", "daylight", "deadline",
            "decision", "decrease", "delivery", "director", "disaster", "discount", "discover", "distance",
            "district", "division", "document", "donation", "doorbell", "driveway", "duration", "dynamite",
            "earnings", "election", "electron", "elephant", "elevator", "emission", "emphasis", "employee",
            "employer", "engineer", "entrance", "envelope", "equation", "estimate", "exchange", "exercise",
            "exposure", "facility", "feedback", "festival", "football", "forehead", "fountain", "fragment",
            "function", "gardener", "gargoyle", "generals", "giftware", "goldfish", "goodness", "governor",
            "graduate", "grandson", "graphics", "gridiron", "grouping", "guidance", "hardware", "headline",
            "heritage", "homeland", "hospital", "humanity", "hydrogen", "identity", "increase", "industry",
            "instance", "interest", "interior", "internet", "interval", "invasion", "investor", "judgment",
            "junction", "keyboard", "kitchens", "landlord", "landmark", "language", "laughter", "learning",
            "location", "magazine", "magician", "mainland", "majority", "marriage", "material", "mattress",
            "mechanic", "medicine", "memorial", "merchant", "midnight", "military", "minister", "ministry",
            "minority", "mistress", "momentum", "monopoly", "monument", "morality", "mosquito", "mountain",
            "movement", "musician", "necklace", "neighbor", "notebook", "nuisance", "observer", "occasion",
            "offender", "offering", "official", "operator", "opponent", "opposite", "optimism", "organism",
            "original", "outdoors", "overcoat", "overhead", "overview", "painting", "pamphlet", "paradise",
            "parallel", "particle", "passport", "password", "pastries", "patience", "pavilion", "pedestal",
            "personal", "pharmacy", "platform", "pleasure", "portrait", "position", "potatoes", "practice",
            "precinct", "premises", "presence", "pressure", "prestige", "princess", "priority", "prisoner",
            "producer", "progress", "property", "proposal", "prospect", "protocol", "provider", "province",
            "purchase", "quantity", "question", "railroad", "reaction", "receiver", "recovery", "register",
            "relation", "relative", "religion", "reminder", "republic", "research", "resident", "resource",
            "response", "restroom", "revision", "schedule", "scissors", "security", "sentence", "sequence",
            "sergeant", "servants", "shipping", "shoulder", "sickness", "sidewalk", "software", "solution",
            "souvenir", "specimen", "spectrum", "standard", "standing", "stranger", "strategy", "strength",
            "struggle", "students", "supplier", "surprise", "survivor", "swimming", "sympathy", "syndrome",
            "taxpayer", "teaching", "teaspoon", "terminal", "textbook", "training", "transfer", "treasure",
            "treasury", "triangle", "trousers", "umbrella", "universe", "vacation", "validity", "variable",
            "variance", "vehicles", "velocity", "vertical", "vicinity", "viewport", "villager", "violence",
            "wardrobe", "warriors", "weakness", "weddings", "wildlife", "workshop"
        ]
    }
};